### ISSUE TITLE
Error creating rds stack for EnvironmentStage = product

### ISSUE THREAD

**Issue by jordisantamaria** [aws-samples/aws-aurora-cloudformation-samples#1]
Hi, in our project, we are using as environment values:
`EnvironmentStage:
    Type: String
    Description: The environment tag is used to designate the Environment Stage of the associated AWS resource.
    AllowedValues:
      - develop
      - staging
      - product
    Default: develop`

For develop seems no problem, but when I try to create the product environment, the stack is giving error, can't create rotation lambda.

When I check cloudwatch log in  **/aws/lambda/SecretsManager-SecretRotationFn-stackname** ,
I see this error:

`[ERROR] ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for VersionId: 99542ad5-90bb-466a-b94b-d68e0c48f712`

I think this error is happening because If I check logging before the error, It's creating secret with wrong name, It's putting **prod** instead of **product** in the name, but I'm not using prod in my template anywhere.

`[INFO]	2021-01-06T09:02:53.425Z	de4c8306-ab24-4594-8e87-82889466c6b9	createSecret: Successfully put secret for ARN arn:aws:secretsmanager:us-east-1:017212038965:secret:prod/aurora-pg/ep2as-product-rds-phqqY5 and version 99542ad5-90bb-466a-b94b-d68e0c48f712.`

It's only happening for product, for develop It's working as expected.

For create the name, I'm obviously using same as the template, I only changed EnvironmentStage values of the template:

```
AuroraMasterSecret:
    Condition: IsNotUseDBSnapshot
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['/', [!Ref EnvironmentStage, 'aurora-pg', !Ref 'AWS::StackName']]
      Description: !Join ['', ['Aurora PostgreSQL Master User Secret ', 'for CloudFormation Stack ', !Ref 'AWS::StackName']]
      Tags:
        -
          Key: EnvironmentStage
          Value: !Ref EnvironmentStage
        -
          Key: DatabaseEngine
          Value: 'Aurora PostgreSQL'
        -
          Key: StackID
          Value: !Ref 'AWS::StackId'
      GenerateSecretString:
        SecretStringTemplate: !Join ['', ['{"username": "', !Ref DBUsername, '"}']]
        GenerateStringKey: "password"
        ExcludeCharacters: '"@/\'
        PasswordLength: 16
```

I guess I will be forced to use prod as EnvironmentStage, since I can't find the source code of the lambda SecretsManager-SecretRotationFn-stackname for fix this bug, but It would be nice If you could fix this bug.
